CLASS LHC_ZCITR_YSTUD_MAIN_TABLE301 DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.
    METHODS:
      GET_GLOBAL_AUTHORIZATIONS FOR GLOBAL AUTHORIZATION
        IMPORTING
           REQUEST requested_authorizations FOR ZcitrYstudMainTable301
        RESULT result.
ENDCLASS.

CLASS LHC_ZCITR_YSTUD_MAIN_TABLE301 IMPLEMENTATION.
  METHOD GET_GLOBAL_AUTHORIZATIONS.
  ENDMETHOD.
ENDCLASS.
